# Generated by Django 3.1.2 on 2020-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions1',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions2',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
